const TripsActionTypes = {
    FETCH_TRIPS: "FETCH_TRIPS",
    FETCH_SINGLE_TRIP: "FETCH_SINGLE_TRIP",
    ADD_TRIP: "ADD_TRIP",
    DELETE_TRIP: "DELETE_TRIP",
    UPDATE_TRIP:" UPDATE_TRIP",
    FETCH_WEATHER: "FETCH_WEATHER",
    FETCH_IMAGE: "FETCH_IMAGE"
}

export default TripsActionTypes;