const FlightsActionTypes = {
    FETCH_AIRPORT_SUCCESS: "FETCH_AIRPORT_SUCCESS",
    FETCH_ITINERARY_SUCCESS: "FETCH_ITINERARY_SUCCESS",
    FETCH_ERROR: "FETCH_ERROR",
}

export default FlightsActionTypes;