const FlightsActionTypes = {
    FETCH_DESTINATION_SUCCESS: "FETCH_DESTINATION_SUCCESS",
    FETCH_INFORMATION_SUCCESS: "FETCH_INFORMATION_SUCCESS",
    FETCH_ERROR: "FETCH_ERROR",
}

export default FlightsActionTypes;