const HotelsActionTypes = {
    FETCH_HOTELS: "FETCH_HOTELS",
    FETCH_SINGLE_HOTEL: "FETCH_SINGLE_HOTEL",
    ADD_HOTEL: "ADD_HOTEL",
    DELETE_HOTEL: "DELETE_HOTEL",
    UPDATE_HOTEL:" UPDATE_HOTEL"
}