const ActivitiesActionTypes = {
    FETCH_ACTIVITIES: "FETCH_ACTIVITIES",
    FETCH_SINGLE_ACTIVITY: "FETCH_SINGLE_ACTIVITY",
    ADD_ACTIVITY: "ADD_ACTIVITY",
    DELETE_ACTIVITY: "DELETE_ACTIVITY",
    UPDATE_ACTIVITY:" UPDATE_ACTIVITY"
}

export default ActivitiesActionTypes;