const UserActionTypes = {
  FETCH_USER: "FETCH_USER",
  UPDATE_USER: "UPDATE_USER",
  SIGNUP_USER: "SIGNUP_USER",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  LOGIN_GOOGLE: "LOGIN_GOOGLE",
};

export default UserActionTypes;
