const UserActionTypes = {
  FETCH_USER: "FETCH_USER",
  FETCH_COLLABORATOR: "FETCH_COLLABORATOR",
  UPDATE_USER: "UPDATE_USER",
  SIGNUP_USER: "SIGNUP_USER",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  LOGIN_GOOGLE: "LOGIN_GOOGLE",
  SET_LOGIN_STATUS: "SET_LOGIN_STATUS",
  DELETE_USER: "DELETE_USER",
  REMOVE_COLLABORATOR: "REMOVE_COLLABORATOR",
  CLEAR_COLLABORATORS: "CLEAR_COLLABORATORS",
  ADD_COLLABORATOR: "ADD_COLLABORATOR",
};

export default UserActionTypes;
